// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stone.Infrastructure.DataContextLayer;

namespace Stone.Infrastructure.Migrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20200314032930_Employee-v2")]
    partial class Employeev2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Stone.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Admissao");

                    b.Property<string>("Cpf");

                    b.Property<string>("Nome");

                    b.Property<bool>("PlanoDental");

                    b.Property<bool>("PlanoSaude");

                    b.Property<decimal>("SalarioBruto");

                    b.Property<string>("Setor");

                    b.Property<string>("SobreNome");

                    b.Property<bool>("ValeTransporte");

                    b.HasKey("Id")
                        .HasName("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
